name: Comment on PR for Markdown Changes

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.rst'

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in .md and .rst files
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qvE '.*\.(md|rst)$'; then
            echo "Skipping workflow since changes are made to other file types."
            exit 0
          fi

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            This commit only makes changes to documentation, please use [ci_skip] in future commit messages to save on CI minutes