name: Comment on PR for Markdown Changes

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.rst'
    types: [opened, edited, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Markdown and reStructuredText files
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.(md|rst)$'; then
            echo "Documentation files changed. Triggering comment action."
          else
            echo "No documentation changed. Skipping comment action."
            exit 78 # Exit with a neutral status code to indicate no action is needed
          fi

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This commit only makes changes to documentation, please use [ci_skip] in future commit messages to save on CI minutes