name: Comment on PR for Markdown Changes

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.rst'

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for other changes
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | -qE '\.(md|rst)$'; then
            echo "Other files changed, exiting workflow"
            exit 0
          else
            echo "No other files changed, continuing workflow"
          fi

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            This commit only makes changes to documentation, please use [ci_skip] in future commit messages to save on CI minutes