name: Initiate Test Rich Module

# on:
#   pull_request:
#     paths:
#       - 'rich/**'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install and configure Poetry
        # TODO: workaround for https://github.com/snok/install-poetry/issues/94
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.3.1
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Format check with black
        run: |
          source $VENV
          make format-check
      - name: Typecheck with mypy
        run: |
          source $VENV
          make typecheck
      - name: Cache .pytest_cache directory
        uses: actions/cache@v3
        id: pytest-cache
        with:
          path: tests/.pytest_cache
          key: ${{ runner.os }}-pytest-${{ hashFiles('**/test_*.py') }}
          restore-keys: |
            ${{ runner.os }}-pytest-
      - name: Test with pytest (with coverage)
        run: |
          source $VENV
          pytest tests -v -x --cov=./rich --cov-report=xml:./coverage.xml --cov-report term-missing --rank --rank-weight=1-0-0
        continue-on-error: true
      - name: Create issue on failure
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues
          title: Test failed
          body: The tests failed. Click here to rerun the workflow.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: rich
          flags: unittests
          env_vars: OS,PYTHON
